FROM golang:1.21

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Run tests
CMD ["go", "test", "-v", "./pkg/..."] 